### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by prathameshg-finzly** [gabrielpetersson/fast-grid#10]
Is this project safe for production use?
Can you share how to get started using this?

**Comment by gabrielpetersson** [comment]
it's mostly a demonstrative example rn, i would only use it if i needed a super high speed table on huge data. i'd probably just copy the code over and remove/add code as needed

there is a full example here which is the website
https://github.com/gabrielpetersson/fast-grid/tree/master/example

**Comment by prathameshg-finzly** [comment]
Okay, thanks!
